# Generated by Django 4.0.4 on 2022-05-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FreeCounselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('Class', models.CharField(choices=[('11th', '11th'), ('12th', '12th')], max_length=100)),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], max_length=10)),
                ('combination', models.CharField(max_length=1000)),
                ('career', models.CharField(max_length=1000, verbose_name='Career Choice After 12th')),
            ],
        ),
        migrations.CreateModel(
            name='Membership10th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=1000, verbose_name='Name of Father')),
                ('focc', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Father's Occupation")),
                ('fcon', models.CharField(max_length=1000, verbose_name="Father's Contact Number")),
                ('fmail', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Father's Email Id")),
                ('mname', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name of Mother')),
                ('mocc', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Mother's Occupation")),
                ('mcon', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Mother's Contact Number")),
                ('mmail', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Mother's Email Id")),
                ('name', models.CharField(max_length=1000, verbose_name='Name of the Student')),
                ('Class', models.CharField(max_length=1000, verbose_name='Class studying')),
                ('contact', models.CharField(max_length=10, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(max_length=1000, verbose_name='Name of the school studying')),
                ('city', models.CharField(max_length=1000, verbose_name='City / Town / Place')),
                ('district', models.CharField(max_length=1000, verbose_name='District')),
                ('state', models.CharField(max_length=1000, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name')),
                ('dob', models.DateField(verbose_name='Date of birth:')),
                ('contact', models.CharField(max_length=1000, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=1000, verbose_name='Job Title:')),
                ('subject', models.CharField(max_length=1000, verbose_name='Subject Specialization')),
                ('school', models.CharField(max_length=1000, verbose_name='School / College Working For: ')),
                ('city', models.CharField(max_length=1000, verbose_name='City / Town / Place')),
                ('district', models.CharField(max_length=1000, verbose_name='District')),
                ('state', models.CharField(max_length=1000, verbose_name='State')),
                ('exp', models.CharField(max_length=1000, verbose_name='Working experience in years:')),
                ('qualification', models.CharField(max_length=1000, verbose_name='Highest Education Qualification :')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scholorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Name of the Student')),
                ('contact', models.CharField(max_length=10, verbose_name='Contact / Whatsapp Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], max_length=10)),
                ('combination', models.CharField(max_length=1000)),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('present_school', models.TextField(verbose_name='Name of School/ College studied in 12th:')),
                ('marks', models.CharField(max_length=100, verbose_name='% of Marks Obtained in PUC')),
                ('course', models.CharField(max_length=100, verbose_name='Name of Course joined after 12th:')),
                ('college', models.CharField(max_length=100, verbose_name='Name of the college joined after 12th:')),
                ('fees', models.CharField(max_length=1000, verbose_name='Total estimated Fees:')),
                ('income', models.CharField(max_length=1000, verbose_name='Annual Family Income:')),
                ('loan', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=1000, verbose_name='Availing Education Loan:')),
            ],
        ),
        migrations.CreateModel(
            name='Membership12th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=1000, verbose_name='Name of Father')),
                ('focc', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Father's Occupation")),
                ('fcon', models.CharField(max_length=1000, verbose_name="Father's Contact Number")),
                ('fmail', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Father's Email Id")),
                ('mname', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Name of Mother')),
                ('mocc', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Mother's Occupation")),
                ('mcon', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Mother's Contact Number")),
                ('mmail', models.CharField(blank=True, max_length=1000, null=True, verbose_name="Mother's Email Id")),
                ('name', models.CharField(max_length=1000, verbose_name='Name of the Student')),
                ('wno', models.CharField(max_length=1000, verbose_name="Student's Whatsapp Number")),
                ('email', models.EmailField(max_length=254, verbose_name='Email Id')),
                ('Class', models.CharField(choices=[('11th', '11th'), ('12th', '12th')], max_length=100)),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], max_length=10)),
                ('combination', models.CharField(max_length=1000)),
                ('college', models.CharField(max_length=1000, verbose_name='College Name')),
                ('city', models.CharField(max_length=1000, verbose_name='City / Town / Place')),
                ('religion', models.CharField(blank=True, max_length=100, null=True)),
                ('caste', models.CharField(blank=True, max_length=100, null=True)),
                ('career', models.CharField(max_length=1000, verbose_name='Career Choice After 12th')),
                ('assistance', models.ManyToManyField(blank=True, null=True, to='main.assistancechoices', verbose_name='What assistance you looking for:')),
            ],
        ),
    ]
